Template
LogoFX/Samples.Bootstrapping pull request #2
Opened 2020-04-23 15:46 UTC by dmitrybublik

2020-04-24 10:02 UTC, godrose commented
@dmitrybublik Please add example of usage

2020-04-24 13:55 UTC, godrose commented on logofx_client_bootstrapping_samples/.template.config/template.json
> +  "sourceName": "logofx_client_bootstrapping_samples",              // Will replace the string 'logofx_client_bootstrapping_samples' with the value provided via -n.
check the namespaces issue

2020-04-24 13:57 UTC, godrose commented on logofx_client_bootstrapping_samples/App.xaml
> +﻿<Application x:Class="logofx_client_bootstrapping_samples.App"
Check namespace

2020-04-24 13:57 UTC, godrose commented on logofx_client_bootstrapping_samples/App.xaml.cs
> +namespace logofx_client_bootstrapping_samples
check namespaces

2020-04-24 13:57 UTC, godrose commented on logofx_client_bootstrapping_samples/AppBootstrapper.cs
> +namespace logofx_client_bootstrapping_samples
check namespace

2020-04-24 13:57 UTC, godrose commented on logofx_client_bootstrapping_samples/AppBootstrapper.cs
> +            Prefixes = new[] { "logofx_client_bootstrapping_samples" }
check namespace

2020-04-24 14:07 UTC, glyad approved these changes

2020-04-26 02:32 UTC, godrose requested changes

2020-04-26 02:32 UTC, godrose commented on LogoFX.Samples.Client.Bootstrapping/.template.config/template.json
> +  "sourceName": "LogoFX.Samples.Client.Bootstrapping",              // Will replace the string 'LogoFX.Client.Bootstrapping.Samples' with the value provided via -n.
Shouldn't it be "LogoFX.Samples.Client.Bootstrapping" in both places?

2020-04-27 07:59 UTC, godrose approved these changes

2020-04-27 08:00 UTC, merged